### ISSUE TITLE
Issue with numpy gradient and alphas

### ISSUE THREAD

**Issue by pjneumnn** [gadorlhiac/PyLDM#3]
Error occurs when, for example, following the steps in the manual to perform LDA. The program returns:

> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\lib-tk\Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "main.py", line 395, in mat_lda
    self.LDAnalyzer.run_LDA(self.GA_taus)
  File "fit\lda.py", line 48, in run_LDA
    lcurve_x, lcurve_y, k = self._lcurve()
  File "fit\lda.py", line 185, in _lcurve
    k = self._calc_k(lcurve_x, lcurve_y)
  File "fit\lda.py", line 196, in _calc_k
    dx = np.gradient(lx, da)
  File "C:\ProgramData\Anaconda2\lib\site-packages\numpy\lib\function_base.py", line 1598, in gradient
    raise ValueError("distances must be scalars")
ValueError: distances must be scalars

This suggests that _np.isscalar(da)_ returns _false_ for some reason, but I can't figure out why, maybe an issue with how self.alphas is updated since we have _da=np.gradient(self.alphas)_. Although it could also just be my python/numpy setup/versions. Can anyone reproduce this?

**Comment by pjneumnn** [comment]
**Possible workaround**

The error occurs in this section of _pyldm.py_ (line 189 to 201)

    # Curvature function, for finding optimal alpha on L-curve
    def _calc_k(self, lx, ly):
        #dx = np.gradient(lx)
        #dy = np.gradient(ly, dx)
        #d2y = np.gradient(dy, dx)
        #k = abs(d2y)/(1+dy**2)**(1.5)
        da = np.gradient(self.alphas)
        dx = np.gradient(lx, da)
        dy = np.gradient(ly, da)
        d2x = np.gradient(dx, da)
        d2y = np.gradient(dy, da)
        k = (dx*d2y - d2x*dy)/(dx**2 + dy**2)**(1.5)
        return k

where _np.gradient_ won't take _da_, as an argument and returns the error above. Since _self.alphas_ is defined using _np.linspace_, the gradient of _self.alphas_ returns an array filled with the same number throughout, since the gradient is linear by definition. We can now just grab the first number out of that array and _np.gradient_ will take care of the dimensionality. LDA then proceeds just fine.

We change  da = np.gradient(self.alphas) to da = np.gradient(self.alphas)**[0]**

    # Curvature function, for finding optimal alpha on L-curve
    def _calc_k(self, lx, ly):
        #dx = np.gradient(lx)
        #dy = np.gradient(ly, dx)
        #d2y = np.gradient(dy, dx)
        #k = abs(d2y)/(1+dy**2)**(1.5)
        da = np.gradient(self.alphas)[0]
        dx = np.gradient(lx, da)
        dy = np.gradient(ly, da)
        d2x = np.gradient(dx, da)
        d2y = np.gradient(dy, da)
        k = (dx*d2y - d2x*dy)/(dx**2 + dy**2)**(1.5)
        return k

However I feel like this doesn't really get to the bottom of the issue as to why np.gradient returns the error mentioned above.

**Comment by gadorlhiac** [comment]
I'm sorry that you've been getting this error.  I am unable to recreate it with my version of python (2.7.13) and numpy (1.10.4).  What versions are you using? In principle though you should be able to pass an array to the function regardless, according to the current Numpy documentation.
The np.isscalar(da) will return False because da is an array, np.isscalar(da[0]) for instance returns True.  Does the error still occur if the curvature is calculated the other way (uncomment the dx,dy,d2y and k lines)?

**Comment by pjneumnn** [comment]
No problem, not your fault! It does actually appear to be some kind of version error. I run the same version of python but had numpy 1.12.1 installed. I've downgraded to numpy 1.11.0 and the problem dissappears. Also you are of course correct, np.isscalar(da) will return false. Rather, what I meant to say is that

```
if any([not np.isscalar(dxi) for dxi in dx]):
     raise ValueError("distances must be scalars")
```

seems to be triggered. Incidentally this piece of code (https://github.com/numpy/numpy/blob/v1.12.0/numpy/lib/function_base.py#L1597-L1598) seems to have been added to np.gradient in version 1.12.0 and does not appear in previous versions. It also seems that numpy 1.13.0 performs this check in a different manner, so it might be worth finding out if the issue exists there as well or if it is resolved. I will try to get around to this later.
